# Outputs generated by main.tf
output "ssh_key_name" {
    description = "SSH Key for instance login"
    value = alicloud_key_pair.vpn-nat-example-ssh-key.key_file
}

output "user_login" {
    description = "Login name for ECS instance"
    value = "root"
}

output "instance_private_ip" {
    description = "ECS Instance private IP address"
    value = alicloud_instance.vpn-nat-example-ecs.private_ip
}

