# Outputs generated by main.tf
output "ssh_key_name" {
    description = "SSH Key for instance login"
    value = "${alicloud_key_pair.flowlog-example-ssh-key.key_file}"
}

output "user_login" {
    description = "Login name for ECS instance"
    value = "root"
}

# ECS instance public IP addresses
output "ecs_public_ip_a" {
    description = "ECS instance public IP, instance A"
    value = "${alicloud_instance.flowlog-example-ecs-a.public_ip}"
}

output "ecs_public_ip_b" {
    description = "ECS instance public IP, instance B"
    value = "${alicloud_instance.flowlog-example-ecs-b.public_ip}"
}
