# Outputs generated by main.tf
output "ssh_key_name" {
  description = "SSH Key for EC2 instance login"
  value       = "${aws_key_pair.ec2-example-ssh-key.key_name}"
}

output "user_login" {
  description = "Login name for EC2 instance"
  value       = "ubuntu"
}

output "public_ip" {
  description = "EC2 instance public IP address (for bastion host)"
  value       = "${aws_instance.ec2-example-instance.public_ip}"
}
