#
# Variables used in main.tf
#
# You can set default CIDR block, region, and even 
# availability zone here if you like, but I STRONGLY
# recommend you supply your access key and secret
# either as command line arguments (using the "-var" flag)
# or via environment variables, rather than putting
# them into this file
variable "access_key" {
  description = "Your Alibaba Cloud Access Key (AK Key)"
}

variable "access_key_secret" {
  description = "Your Alibaba Cloud Access Key Secret (AK Secret or Secret Key)"
}

variable "public_key_file" {
  description = "Name of SSH key generated by setup.sh. DO NOT CHANGE unless you have also updated setup.sh"
  default = "dev-staging-test-ssh-key.pub"
}

variable "region" {
  description = "The Alibaba Cloud region where you want to launch your instance (for example cn-hongkong or ap-southeast-1)"
  default     = "ap-southeast-1"
}
